apiVersion: apps/v1
kind: Deployment
metadata:
  name: fip-telegram-bot
spec:
  selector:
    matchLabels:
      app: fip-telegram-bot
  template:
    metadata:
      labels:
        app: fip-telegram-bot
    spec:
      containers:
      - name: fip-telegram-bot
        env:
        - name: FIP_API_HOST
          value: "whats-on-fip"
        - name: FIP_API_PORT
          value: "1919"
        - name: SPOTIFY_API_HOST
          value: "spotify-api"
        - name: SPOTIFY_API_PORT
          value: "1919"
        envFrom:
        - secretRef:
            name: fip-telegram-bot
        image: dixneuf19/fip-telegram-bot:4461ccf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: fip-telegram-bot
# spec:
#   selector:
#     app: fip-telegram-bot
#   ports:
#   - port: 80
#     targetPort: 80
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: fip-telegram-bot
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - fip-telegram-bot.dixneuf19.me
#     secretName: fip-telegram-bot-dixneuf19-me-tls
#   rules:
#   - host: fip-telegram-bot.dixneuf19.me 
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: fip-telegram-bot
#           servicePort: 80
