# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dixneuf19/fip-telegram-bot
  tag: latest
  pullPolicy: Always

container:
  port: 80
  probe: 

resources:
  limits:
    memory: '128Mi'
    cpu: '300m'
  requests:
    memory: '64Mi'
    cpu: '100m'


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  annotations: 
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: leresolver
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: fip-telegram-bot.dixneuf19.me
  hosts: 
  - host: "fip-telegram-bot.dixneuf19.me"
    paths:
      - path: "/"
  # tls: true

configmap: 
 FIP_API_HOST: "whats-on-fip"
 FIP_API_PORT: 1919
 SPOTIFY_API_HOST: "spotify-api"
 SPOTIFY_API_PORT: 1919
 BOT_WEBHOOK_PATH: some_random_path

secrets:
  - name: fip-telegram-bot
    key: BOT_TELEGRAM_TOKEN
